## Uncomment the include lines to match your preferences

####################################################
## THE COMPOSE KEY
####################################################

## The CapsLock key acts as "Compose"
# include "compose-caps.inc"

## The Menu key acts as "Compose"
# include "compose-menu.inc"

## The right Alt key acts as "Compose"
# include "compose-ralt.inc"

## The right Win key acts as "Compose"
# include "compose-rwin.inc"

## The CapsLock key acts as "Control"
# include "ctrl-nocaps.inc"

## Swap the CapsLock and the left Control keys
# include "ctrl-swapcaps.inc"

###########################################################
## CHANGING THE GROUP
###########################################################

## The following options control how the keyboard changes its layout.
## They are useful mostly for the non-Latin layouts and control how
## to toggle the keyboard between "Latin" and "non-Latin" mode.  They
## can be useful in other circumstances also (e.g. toggling between
## "QWERTY" and "Dvorak" layouts).

## The left Alt key changes the keyboard layout
# include "grp-toggle.inc"

## The CapsLock key changes the keyboard layout
## Use the Shift+CapsLock combination for the usual behaviour of CapsLock
# include "grp-caps_toggle.inc"

## Any of the Win keys changes the keyboard layout
# include "grp-win_switch.inc"

## The Menu key changes the keyboard layout
# include "grp-menu_toggle.inc"

## The right Control changes the keyboard layout
# include "grp-rctrl_toggle.inc"

## The right Shift changes the keyboard layout
# include "grp-rshift_toggle.inc"

## The right Win key changes the keyboard layout
# include "grp-rwin_toggle.inc"

## The ScrollLock key changes the keyboard layout
# include "grp-sclk_toggle.inc"

## The left Alt key changes the keyboard layout
# include "grp-lalt_toggle.inc"

## The left Control key changes the keyboard layout
# include "grp-lctrl_toggle.inc"

## The left Shift key changes the keyboard layout
# include "grp-lshift_toggle.inc"

## The left Win key changes the keyboard layout
# include "grp-lwin_toggle.inc"

## Alt+Shift combination changes the keyboard layout
# include "grp-alt_shift_toggle.inc"

## Control+Alt combination changes the keyboard layout
# include "grp-ctrl_alt_toggle.inc"

## Control+Shift combination changes the keyboard layout
# include "grp-ctrl_shift_toggle.inc"

## The right Alt key switches the keyboard layout only while pressed
# include "grp-switch.inc"

## The left Alt key switches the keyboard layout only while pressed
# include "grp-lswitch.inc"

## The left Win key switches the keyboard layout only while pressed
# include "grp-lwin_switch.inc"

## The right Win key switches the keyboard layout only while pressed
# include "grp-rwin_switch.inc"

## The followint three options does not work on the console
# include "grp-alts_toggle.inc"
# include "grp-ctrls_toggle.inc"
# include "grp-shift_toggle.inc"

###########################################################
## CHANGING THE LEVEL
###########################################################

## The following options control how to activate the additional
## symbols that the keyboard can generate.  In many of the Latin
## layouts most of these symbols are accented letters or dead keys.

## The right Control selects the additional symbols
# include "lv3-switch.inc"

## The right Alt selects the additional symbols.  Shift+Alt is Compose.
# include "lv3-ralt_switch_multikey.inc"

## The right Alt selects the additional symbols
# include "lv3-ralt_switch.inc"

## The Menu key selects the additional symbols
# include "lv3-menu_switch.inc"

## Any of the Win keys selects the additional symbols
# include "lv3-win_switch.inc"
## The rigth Win selects the additional symbols
# include "lv3-rwin_switch.inc"

## The left Win key selects the additional symbols 
# include "lv3-lwin_switch.inc"

