#!/bin/sh

#     setupcon -- setup the font and keyboard on the Linux console
#     Copyright © 1999,2000,2001,2002,2003,2006 Anton Zinoviev
#     Portions based on the keymap.sh script of the console-common package
#     Copyright © 2001 Yann Dirson
#     Copyright © 2001 Alcove http://www.alcove.fr/

#     This program is free software; you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation; either version 2 of the License, or
#     (at your option) any later version.

#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.

#     If you have not received a copy of the GNU General Public License
#     along with this program, write to the Free Software Foundation, Inc.,
#     59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

if [ -f /etc/default/console-setup ]; then
    . /etc/default/console-setup
fi

if [ "$VERBOSE_OUTPUT" = yes ]; then
    verbose=''
else
    verbose='>/dev/null 2>&1'
fi

case `readlink /proc/self/fd/0` in
    /dev/tty[0-9]*|/dev/vc/[0-9]*|/dev/console)
	;;
    *)
        # Exit silently when we are not on the Linux console
	exit 0 
	;;
esac

# On Mac PPC machines, we may need to set kernel vars first
# We need to mount /proc to do that; not optimal, as its going to 
# be mounted in S10checkroot, but we need it set up before sulogin
# may be run in checkroot, which will need the keyboard to log in...
if [ -x /sbin/sysctl ] && [ -r /etc/sysctl.conf ]; then
    if grep -v '^\#' /etc/sysctl.conf | grep -q keycodes ; then
	grep keycodes /etc/sysctl.conf | grep -v "^#" \
	    | while read d ; do
	    /sbin/sysctl -w $d 2> /dev/null || true
	done
    fi
fi

if [ "$ACTIVE_CONSOLES" ]; then
    for console in $ACTIVE_CONSOLES; do
	if [ "$CHARMAP" = UTF-8 ] || [ -z "$ACM" ]; then
	    /bin/echo -n -e '\033%G' >$console
	else
	    /bin/echo -n -e '\033%@' >$console
	fi
	if [ ! -f "$FONT" ]; then
	    FONT=/etc/console-setup/$CODESET-$FONTFACE$FONTSIZE.psf.gz
	fi
	if [ -f "$FONT" ]; then
	    if which consolechars >/dev/null; then
		eval consolechars -v --tty=$console -f "$FONT" $verbose
	    elif which setfont >/dev/null; then
		eval setfont -v -C $console "$FONT" $verbose
	    fi
	fi
	if [ ! -f "$ACM" ]; then
	    ACM=/etc/console-setup/$CHARMAP.acm.gz
	fi
	if [ "$CHARMAP" != UTF-8 ] && [ -f "$ACM" ]; then
	    if which consolechars >/dev/null; then
		eval consolechars -v --tty=$console \
		    --acm "$ACM" $verbose
	    elif which setfont >/dev/null; then
		eval setfont -v -C -m "$ACM" $verbose
	    fi	    
	fi
    done
fi
if which kbd_mode >/dev/null; then
    if [ "$CHARMAP" = UTF-8 ] || [ -z "$ACM" ]; then
	kbd_mode -u
    else
	kbd_mode -a
    fi	
fi
if \
    which loadkeys >/dev/null \
    && [ -f /etc/console-setup/boottime.kmap.gz ]
    then
    eval loadkeys /etc/console-setup/boottime.kmap.gz $verbose
fi
