#!/bin/sh

set -e

CONFIGDIR=/etc/console-setup
CONFIGFILE=/etc/default/console-setup

# Source debconf library.
. /usr/share/debconf/confmodule

fontdir=/usr/share/consolefonts

if [ "$1" = "configure" ]; then
    
    db_get console-setup/codeset
    codeset="$RET"
    db_get console-setup/fontface
    fontface="$RET"
    db_get console-setup/fontsize
    fontsize="$RET"

    fontname=$codeset-$fontface$fontsize.psf.gz
    
    db_get console-setup/charmap
    charmap="$RET"

    db_get console-setup/ttys
    ttys="$RET"


    db_get console-setup/modelcode
    model="$RET"

    db_get console-setup/layoutcode
    layout="$RET"

    db_get console-setup/variantcode
    variant="$RET"

    db_get console-setup/optionscode
    options="$RET"

    [ -f $CONFIGDIR/$fontname ] || cp $fontdir/$fontname $CONFIGDIR/

    if [ "$charmap" != UTF-8 ]; then
	[ -f $CONFIGDIR/$charmap.acm.gz ] \
	    || cp /usr/share/consoletrans/$charmap.acm.gz $CONFIGDIR/
	acm=$CONFIGDIR/$charmap.acm.gz
	acm_option="-charmap $charmap"
    else
	acm=''
	acm_option=''
    fi

    if [ ! -e $CONFIGFILE ]; then
	cat /usr/share/doc/console-setup/examples/console-setup >$CONFIGFILE
	cat >>$CONFIGFILE <<EOF

# Do not update the following md5 sum if you change
# $CONFIGDIR/boottime.kmap.gz and Debconf will not overwrite
# your custom keymap.  Do not update it even if you want to make
# Debconf overwrite it.  Instead simply specify the empty string as
# a md5 sum.

BOOTTIME_KMAP_MD5=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
EOF
    fi

    . $CONFIGFILE || true

    if \
	[ -z "$BOOTTIME_KMAP_MD5" ] \
	|| [ ! -f "$CONFIGDIR/boottime.kmap.gz" ] \
	|| echo "$BOOTTIME_KMAP_MD5  $CONFIGDIR/boottime.kmap.gz" \
	    | md5sum -c 2>/dev/null >/dev/null
    then
	ckbcomp $acm_option -model "$model" "$layout" "$variant" "$options" \
	    | gzip -9 >$CONFIGDIR/boottime.kmap.gz
	BOOTTIME_KMAP_MD5=`md5sum $CONFIGDIR/boottime.kmap.gz | sed 's/ .*//'`
    fi

    # Ensure we do not mess up the config file's ownership and permissions.
    cp -a -f $CONFIGFILE $CONFIGFILE.tmp

    # If the admin deleted or commented some variables but then set
    # them via debconf, (re-)add them to the conffile.
    for var in \
	ACTIVE_CONSOLES CHARMAP CODESET FONTFACE FONTSIZE \
	XKBMODEL XKBLAYOUT XKBVARIANT XKBOPTIONS BOOTTIME_KMAP_MD5
    do
        if ! grep "^ *${var}=" $CONFIGFILE >/dev/null; then
	    echo "${var}=" >>$CONFIGFILE
	fi
    done    
    
    awk '
/^ *ACTIVE_CONSOLES=/ { print "ACTIVE_CONSOLES=\"'$ttys'\""; next; }
/^ *CHARMAP=/ { print "CHARMAP=\"'$charmap'\""; next; }
/^ *CODESET=/ { print "CODESET=\"'$codeset'\""; next; }
/^ *FONTFACE=/ { print "FONTFACE=\"'$fontface'\""; next; }
/^ *FONTSIZE=/ { print "FONTSIZE=\"'$fontsize'\""; next; }
/^ *XKBMODEL=/ { print "XKBMODEL=\"'$model'\""; next; }
/^ *XKBLAYOUT=/ { print "XKBLAYOUT=\"'$layout'\""; next; }
/^ *XKBVARIANT=/ { print "XKBVARIANT=\"'$variant'\""; next; }
/^ *XKBOPTIONS=/ { print "XKBOPTIONS=\"'$options'\""; next; }
/^ *BOOTTIME_KMAP_MD5=/ {
    print "BOOTTIME_KMAP_MD5=\"'$BOOTTIME_KMAP_MD5'\"";
    next;
}
{ print; }
' <$CONFIGFILE >$CONFIGFILE.tmp
    
    mv -f $CONFIGFILE.tmp $CONFIGFILE
fi

#DEBHELPER#
